### ISSUE TITLE
The best practices

### ISSUE THREAD

**Issue by thelastinuit** [TheClowder/guides#1]
@mayra-cabrera 

I was thinking (yes I have a brain not just big muscles and sexy pants) what sort of best practices we should follow. I guess that every language will have their own. The purpose of this issue is to sort decide from where we will take these best practices or what we should keep for each of them.

**Comment by thelastinuit** [comment]
Also, which services will be using like Travis and so... obviously cheaper perhaps free!!!

**Comment by mayra-cabrera** [comment]
Nice! 

@thelastinuit or _as you're mostly known in the underworld "Mr. Sexy Pants"_

Are you talking about creating our own guides? With markdown files and all that? If that's so I'm all in, if not shame on you! 

For Golang guides I think we can pretty much follow/copycat the [Effective Go](https://golang.org/doc/effective_go.html) & [How to write Go Code](https://golang.org/doc/code.html) guides, since they establish the conventions for programming in Go. Also since both of us are Vim users, what about if we use [vim-go](https://github.com/fatih/vim-go) plugin? Have you tried? It's pretty neat!

For the services, since all of our projects are going to be open source, I vote for:

- Travis CI for running our tests
- Hound for code review tool 

What do you think?

**Comment by thelastinuit** [comment]
Yeah, guides for these crazy cats, you know standards and perhaps a little bit of being mavericks and set our own.

Travis and Hound it is!

I rarely used vim nowadays, however, in emacs there is something similar as vim-go: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go

**Comment by thelastinuit** [comment]
I guess this discussion resolved itself.
